name: unlimited_things
description: Flutter/Dart package that provides different type of usefully things for your project
version: 0.0.1
homepage: https://github.com/artem312/unlimited_things
repository: https://github.com/artem312/unlimited_things

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.3.0
